/*
 * This file was generated by the Gradle 'init' task.
 */
pluginManagement {
    repositories {
        maven { url = uri("https://repo.spring.io/snapshot") }
        gradlePluginPortal()
    }
}
rootProject.name = "mini-aurora"